# Generated by Django 5.1.7 on 2025-05-02 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_alter_task_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Срок выполнения'),
        ),
    ]
