# Generated by Django 5.1.7 on 2025-05-06 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_file_author'),
        ('users', '0010_alter_managerdepartment_assistant_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsible_department', to='users.department', verbose_name='Ответственный департамент'),
        ),
    ]
