# Generated by Django 5.1.7 on 2025-05-02 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_employee_email_alter_employee_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Пользователь Активен'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(choices=[('Отдел продаж', 'Отдел продаж'), ('Отдел поддержки клиентов', 'Отдел поддержки клиентов'), ('Отдел разработки', 'Отдел разработки'), ('Отдел маркетинга', 'Отдел маркетинга'), ('Отдел кадров', 'Отдел кадров'), ('Финансовый отдел', 'Финансовый отдел'), ('Юридический отдел', 'Юридический отдел'), ('IT-отдел', 'IT-отдел'), ('Отдел логистики', 'Отдел логистики'), ('Административный отдел', 'Административный отдел'), ('Отдел технической поддержки', 'Отдел технической поддержки'), ('Отдел тестирования', 'Отдел тестирования')], max_length=255, verbose_name='Название департамента'),
        ),
    ]
