# Generated by Django 5.1.7 on 2025-05-03 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_employee_must_change_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='managerdepartment',
            old_name='assistant_mananger',
            new_name='assistant_manager',
        ),
    ]
