# Generated by Django 5.1.7 on 2025-05-05 04:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_employee_must_change_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managerdepartment',
            name='assistant_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager_department_assistant', to=settings.AUTH_USER_MODEL, verbose_name='Заместитель руководителя'),
        ),
    ]
