# Generated by Django 5.1.7 on 2025-05-09 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_managerdepartment_assistant_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(blank=True, choices=[('Менеджер', 'Менеджер'), ('Разработчик', 'Разработчик'), ('Тестировщик', 'Тестировщик'), ('Стажёр', 'Стажёр')], default='', max_length=100, verbose_name='Роль сотрудника'),
        ),
    ]
