# Generated by Django 5.1.7 on 2025-05-09 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_employeeactionhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeactionhistory',
            name='executor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='employee_actions', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employeeactionhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions_on_employee', to=settings.AUTH_USER_MODEL),
        ),
    ]
