# Generated by Django 5.1.7 on 2025-05-09 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_employeeactionhistory_executor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managerdepartment',
            name='assistant_manager',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='manager_department_assistant', to=settings.AUTH_USER_MODEL, verbose_name='Заместитель руководителя'),
        ),
        migrations.AlterField(
            model_name='managerdepartment',
            name='manager',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='manager_department', to=settings.AUTH_USER_MODEL, verbose_name='Руководитель'),
        ),
    ]
