# Generated by Django 5.1.7 on 2025-05-09 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_managerdepartment_assistant_manager_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managerdepartment',
            name='manager',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='manager_department', to=settings.AUTH_USER_MODEL, verbose_name='Руководитель'),
        ),
    ]
