# Generated by Django 5.1.7 on 2025-05-09 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_managerdepartment_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(choices=[('Отдел продаж', 'Отдел продаж'), ('Отдел разработки', 'Отдел разработки'), ('Отдел кадров', 'Отдел кадров'), ('Отдел системного администрирования', 'Отдел системного администрирования'), ('Отдел технической поддержки', 'Отдел технической поддержки'), ('Отдел тестирования', 'Отдел тестирования'), ('Отдел безопасности', 'Отдел безопасности')], max_length=255, verbose_name='Название департамента'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(blank=True, choices=[('Руководитель департамента', 'Руководитель департамента'), ('Заместитель руководителя', 'Заместитель руководителя'), ('Сотрудник технической поддержки', 'Сотрудник технической поддержки'), ('Разработчик', 'Разработчик'), ('Тестировщик', 'Тестировщик'), ('Менеджер по работе с клиентами', 'Менеджер по работе с клиентами'), ('Рекрутер', 'Рекрутер'), ('Системный администратор', 'Системный администратор'), ('Сотрудник службы безопасности', 'Сотрудник службы безопасности')], default='', max_length=100, null=True, verbose_name='Роль сотрудника'),
        ),
        migrations.AlterField(
            model_name='employeeactionhistory',
            name='executor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_actions', to=settings.AUTH_USER_MODEL),
        ),
    ]
