# Generated by Django 5.1.7 on 2025-04-01 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('deadline', models.DateField(db_index=True, verbose_name='Срок выполнения')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата и время создания')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('open', 'Открыта'), ('in_progress', 'В работе'), ('on_review', 'На проверке'), ('closed', 'Завершена')], default='open', max_length=100, verbose_name='Статус задачи')),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий'), ('manager', 'Задача от руководителя департамента')], default='medium', max_length=100, verbose_name='Приоритет')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Автор задачи')),
                ('executors', models.ManyToManyField(blank=True, related_name='executed_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Исполнители')),
            ],
        ),
    ]
