# Generated by Django 5.1.7 on 2025-05-02 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_task_text_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
