# Generated by Django 5.1.7 on 2025-05-09 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_task_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('open', 'Открыта'), ('in_progress', 'В работе')], default='open', max_length=100, verbose_name='Статус задачи'),
        ),
    ]
