# Generated by Django 5.1.7 on 2025-04-30 07:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=100, validators=[django.core.validators.EmailValidator], verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(blank=True, choices=[('Менеджер', 'Менеджер'), ('Разработчик', 'Разработчик'), ('Тестировщик', 'Тестировщик'), ('Стажёр', 'Стажёр')], default='Разработчик', max_length=100, verbose_name='Роль сотрудника'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(blank=True, choices=[('Работает', 'Работает'), ('В отпуске', 'В отпуске'), ('Уволен', 'Уволен')], default='Работает', max_length=50, verbose_name='Статус сотрудника'),
        ),
    ]
