# Generated by Django 5.1.7 on 2025-05-02 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_employee_is_active_alter_department_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='is_active',
        ),
    ]
