# Generated by Django 5.1.7 on 2025-05-03 03:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_employee_must_change_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='must_change_password',
        ),
        migrations.AddField(
            model_name='managerdepartment',
            name='assistant_mananger',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='manager_department_assistant', to=settings.AUTH_USER_MODEL, verbose_name='Заместитель руководителя'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='managerdepartment',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_department', to=settings.AUTH_USER_MODEL, verbose_name='Руководитель'),
        ),
    ]
