# Generated by Django 5.1.7 on 2025-05-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_assistant_mananger_managerdepartment_assistant_manager'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='managerdepartment',
            name='unique_manager_department',
        ),
        migrations.AddField(
            model_name='employee',
            name='must_change_password',
            field=models.BooleanField(default=True),
        ),
        migrations.AddConstraint(
            model_name='managerdepartment',
            constraint=models.UniqueConstraint(fields=('manager', 'assistant_manager', 'department'), name='unique_manager_and_assistant_department'),
        ),
    ]
