# Generated by Django 5.1.7 on 2025-05-03 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_managerdepartment_unique_manager_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='must_change_password',
        ),
    ]
